---
Resources:
  DynamoDBTable:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::DynamoDB::Table"
    DeletionPolicy: "Retain"
    Properties:
      SSESpecification:
        SSEEnabled: false
      ContributorInsightsSpecification:
        Enabled: false
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      TableName: "sasten"
      AttributeDefinitions:
      - AttributeType: "S"
        AttributeName: "GSI1PK"
      - AttributeType: "S"
        AttributeName: "GSI1SK"
      - AttributeType: "S"
        AttributeName: "pk"
      - AttributeType: "S"
        AttributeName: "sk"
      BillingMode: "PAY_PER_REQUEST"
      GlobalSecondaryIndexes:
      - IndexName: "GSI1"
        Projection:
          ProjectionType: "ALL"
          NonKeyAttributes: []
        KeySchema:
        - KeyType: "HASH"
          AttributeName: "GSI1PK"
        - KeyType: "RANGE"
          AttributeName: "GSI1SK"
        ContributorInsightsSpecification:
          Enabled: false
      KeySchema:
      - KeyType: "HASH"
        AttributeName: "pk"
      - KeyType: "RANGE"
        AttributeName: "sk"
      DeletionProtectionEnabled: false
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: "expires"
  IAMUser:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::User"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/"
      ManagedPolicyArns:
      - Ref: "IAMManagedPolicy"
      UserName: "sasten"
  IAMManagedPolicy:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Retain"
    Properties:
      ManagedPolicyName: "sasten"
      Path: "/"
      Description: ""
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Resource:
          - "arn:aws:dynamodb:eu-west-1:692593327170:table/sasten"
          - "arn:aws:dynamodb:eu-west-1:692593327170:table/sasten/index/GSI1"
          Action:
          - "dynamodb:BatchGetItem"
          - "dynamodb:BatchWriteItem"
          - "dynamodb:Describe*"
          - "dynamodb:List*"
          - "dynamodb:PutItem"
          - "dynamodb:DeleteItem"
          - "dynamodb:GetItem"
          - "dynamodb:Scan"
          - "dynamodb:Query"
          - "dynamodb:UpdateItem"
          Effect: "Allow"
          Sid: "DynamoDBAccess"
