/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/pxp4wmTYZ52
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { QuestionsView } from "./questions-view"
import Link from "next/link"
import { ResultsDialog } from "./results-dialog"
import { Leaderboard } from "./leaderboard"
import { QuizHeader } from "./quiz-header"
import Loadable from "./loadable"

export function QuizView(props: any) {
  return (
    <div className="lg:flex lg:flex-col lg:h-screen">
      <div className="flex flex-col min-h-svh lg:min-h-fit lg:h-full">
        <Loadable {...props} />
      </div>
      <footer className="bg-gray-900 text-white py-4 px-6">
        <Leaderboard {...props} showUserStats={true} />
        <div className="text-xs text-gray-300 underline underline-offset-2 text-center lg:text-right">
          <Link href={'https://github.com/selcukcihan/sasten'} target="#blank">Check out the project on GitHub</Link>
        </div>
      </footer>
      <ResultsDialog {...props} />
    </div>
  )
}
