/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/pxp4wmTYZ52
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Session } from "next-auth"

export function Quiz(props: any) {
  const session = props.session as (Session | null)
  return (
    <div className="flex flex-col h-screen">
      <header className="bg-gray-900 text-white py-4 px-6">
        <div className="container mx-auto flex justify-between items-center">
          <h1 className="text-2xl font-bold">Developer Quiz</h1>
          <div className="flex items-center space-x-4">
            <Button size="sm" variant="secondary">
              <ChromeIcon className="h-4 w-4 mr-2" />
              Sign in with Google
            </Button>
          </div>
        </div>
      </header>
      <main className="flex-1 bg-gray-100 dark:bg-gray-800 p-8 flex flex-col items-center justify-center">
        <div className="bg-white dark:bg-gray-900 shadow-lg rounded-lg w-full max-w-3xl p-8">
          <div className="flex items-center justify-between mb-6">
            <div className="text-gray-500 dark:text-gray-400">Question 1 of 10</div>
            <div className="text-gray-500 dark:text-gray-400">Score: 0/10</div>
          </div>
          <h2 className="text-2xl font-bold mb-4">What is the purpose of the foo bar directive in JavaScript?</h2>
          <div className="grid grid-cols-2 gap-4">
            <button className="bg-gray-200 dark:bg-gray-700 dark:text-gray-200 rounded-lg py-3 px-6 hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors">
              Enables strict mode
            </button>
            <button className="bg-gray-200 dark:bg-gray-700 dark:text-gray-200 rounded-lg py-3 px-6 hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors">
              Disables strict mode
            </button>
            <button className="bg-gray-200 dark:bg-gray-700 dark:text-gray-200 rounded-lg py-3 px-6 hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors">
              Enforces type checking
            </button>
            <button className="bg-gray-200 dark:bg-gray-700 dark:text-gray-200 rounded-lg py-3 px-6 hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors">
              Improves performance
            </button>
          </div>
          <div className="flex justify-between mt-6">
            <button className="bg-gray-200 dark:bg-gray-700 dark:text-gray-200 rounded-lg py-3 px-6 hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors">
              Previous
            </button>
            <button className="bg-gray-200 dark:bg-gray-700 dark:text-gray-200 rounded-lg py-3 px-6 hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors">
              Next
            </button>
          </div>
        </div>
      </main>
      <footer className="bg-gray-900 text-white py-4 px-6">
        <div className="container mx-auto flex justify-between items-center">
          <div>
            <h2 className="text-xl font-bold">Leaderboard</h2>
            <p className="text-gray-400">Top 5 scores</p>
          </div>
          <div className="flex flex-col items-end">
            <div className="flex items-center mb-2">
              <div className="bg-yellow-500 text-white font-bold rounded-full w-8 h-8 flex items-center justify-center mr-2">
                1
              </div>
              <div>John Doe - 10/10</div>
            </div>
            <div className="flex items-center mb-2">
              <div className="bg-gray-500 text-white font-bold rounded-full w-8 h-8 flex items-center justify-center mr-2">
                2
              </div>
              <div>Jane Smith - 9/10</div>
            </div>
            <div className="flex items-center mb-2">
              <div className="bg-gray-500 text-white font-bold rounded-full w-8 h-8 flex items-center justify-center mr-2">
                3
              </div>
              <div>Bob Johnson - 8/10</div>
            </div>
            <div className="flex items-center mb-2">
              <div className="bg-gray-500 text-white font-bold rounded-full w-8 h-8 flex items-center justify-center mr-2">
                4
              </div>
              <div>Alice Williams - 7/10</div>
            </div>
            <div className="flex items-center mb-2">
              <div className="bg-gray-500 text-white font-bold rounded-full w-8 h-8 flex items-center justify-center mr-2">
                5
              </div>
              <div>Tom Davis - 6/10</div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}

function ChromeIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="4" />
      <line x1="21.17" x2="12" y1="8" y2="8" />
      <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
      <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
    </svg>
  )
}
